### ISSUE TITLE
[功能/FEATURE]Will a webdav server be added to this project?

### ISSUE THREAD

**Issue by zzeking** [mcthesw/game-save-manager#1]
I think it's a good method to sync files by using webdav.

**Comment by mcthesw** [comment]
I've thought about it. But I need time to learn how to use it. This function may be supported in the future.
我今天想过这个问题，不过我现在还需要学习一下怎么使用，可能在未来的某一天会支持。

**Comment by mcthesw** [comment]
已建立讨论，希望能在近期完成该功能 #66

**Comment by mcthesw** [comment]
功能已实现，测试完毕即可发布
The function has been implemented and will be released after testing is completed
