### ISSUE TITLE
[错误/BUG]v1.1.0版本在win10下打开软件界面呈现白屏

### ISSUE THREAD

**Issue by kongbaiku** [mcthesw/game-save-manager#111]
软件版本：Game save manager V1.1.0
系统版本：Windows 10 专业版 22H2 19045.4291

双击exe，程序纯白，界面无显示，v1.0版本显示正常

![Snipaste_2024-05-14_10-09-07](https://github.com/mcthesw/game-save-manager/assets/68895237/7e0c7ea5-598c-48b0-8b43-7f2769664264)

**Comment by mcthesw** [comment]
该错误已经定位，正在修复中，请先参考以下临时修复方案：
解压`_up_.zip`到同级目录下
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/fc022d59-c505-4b62-ac26-ec118744d9b1)

[_up_.zip下载链接](https://github.com/mcthesw/game-save-manager/files/15301721/_up_.zip)

**Comment by mcthesw** [comment]
这个错误是本次更新引入了多语言文件导致的，便携版忘记把这些文件打包进去了，`_up_`文件夹与`rgsm.exe`同级

**Comment by mcthesw** [comment]
感谢反馈，问题已经修复，可以在release直接下载，网盘文件也已经更新
