### ISSUE TITLE
[错误/BUG]重装系统后一键恢复所有存档错误

### ISSUE THREAD

**Issue by b1344941657** [mcthesw/game-save-manager#117]
**问题简述 Describe the bug**
重装系统后一键恢复所有存档错误
在重装后没有上层文件夹的情况下，点击恢复存档也不会进行恢复，均提示错误

**正确表现 Expected behavior**
请简要描述正常时应该发生什么？（就是在BUG修好之后）
正常应该恢复所有存档

**截图 Screenshots**
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/363791f9-1b22-40c4-aa50-d9370ec978df)
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/08388284-6af2-4868-8a6a-18da0f731f76)

**环境 Desktop:**

 - 操作系统 OS:win10专业版
 - 软件版本 Version [e.g. 22]22h2

**其余信息 Additional context**
你可以在这补充更多信息。
猜测是存档文件夹为创建，比如文件在/a/b/c下，但是a文件夹未创建，所以无法创建或恢复c文件夹的存档，

**Comment by mcthesw** [comment]
是否开启了“应用前额外备份”功能？这个功能会在覆盖前先备份一次，如果文件不存在会导致这个备份失败，从而无法恢复

**Comment by b1344941657** [comment]
试了一下，无论是否开启应用前额外备份功能，都无法恢复，提示错误和截图是一样的，我从0.3开始用的您的软件，一直都有这个问题，之前重装之后，文件夹不存在的情况下恢复就是无法恢复，尝试了新建存档的/a/b/c文件夹后，再次点恢复存档，c文件夹内的存档文件才能正常恢复，即使正常存档多层不存在的路径，只有存档文件夹不存在，也就是设定存档文件夹在/a下，如果我没有手动新建/a文件夹，也是无论如何都无法恢复成功的

**Comment by mcthesw** [comment]
了解了，下次更新前我会检查这个功能

**Comment by mcthesw** [comment]
于V1.1.0版本测试，未复现该问题，见下方步骤

----
1. 目标文件夹（及其上级文件夹）存在，且已经创建备份
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/f78eff38-79b7-4721-bab0-ecae4e8f3bc3)
2. 删除目标文件夹的上级文件夹，点击用最新存档覆盖，成功恢复
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/983103aa-0514-4b25-b2f4-8b16ef5ad441)
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/a3c3b9a4-2637-42b4-a93e-26ac7d1a93cd)
3. 重新删除目标文件夹的上级文件夹，在设置界面选择应用所有存档，同样恢复成功
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/dfcf5534-569e-4128-8f2c-cd284e691aa6)

**Comment by mcthesw** [comment]
经过检查，在早期版本确实存在该bug，但是在[1.0.2版本](https://github.com/mcthesw/game-save-manager/commit/08dd5af159dbdf23fc59a4faf7182363dd80f067)中已经修复了，更新到新版应该就OK了
修复该问题的部分代码如下
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/a3759045-9d2e-4585-b67e-83bb2e4ddf03)

**Comment by b1344941657** [comment]
大佬，可能是没有说清楚，我现在用的版本是1.10版本，现已重装系统，这个问题是在最新版本遇到的
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/99061f41-bbb2-4e97-bdf9-4bde99b16b23)
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/b5c1b934-1345-435b-87a5-2903c7966647)
![PixPin_2024-06-14_21-16-22](https://github.com/mcthesw/game-save-manager/assets/46087744/add00604-364b-4c1b-898e-ccdcfff6cbc2)
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/8291f73d-22aa-4648-9da5-a5d96659abef)
问一下日志怎么提交呢，目前没有找到日志在哪里

**Comment by b1344941657** [comment]
目前试了一下最新版本v1.2，也是会有这个问题
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/bcc4f657-87a9-4aec-82ea-ff9b99ae1456)
![image](https://github.com/mcthesw/game-save-manager/assets/46087744/69ef8683-2518-4a10-9635-a9808c81e88a)
![1](https://github.com/mcthesw/game-save-manager/assets/46087744/c7971f08-5c3d-4510-8ca7-30bfafc6a831)

备份存档文件夹也没有问题，文件都是正常的

**Comment by mcthesw** [comment]
收到反馈，我怀疑是Appdata文件夹的权限问题，因为我之前是在普通目录下尝试恢复的，我再尝试复现一下

**Comment by mcthesw** [comment]
关于日志，现在日志在release模式无法导出，预计下个版本完成该功能

**Comment by mcthesw** [comment]
我注意到动图中提示“无法完成额外备份”，是否是修改设置后没有保存呢？我全局搜索了这个文本，只有在启用了额外备份的情况下会触发这个提示
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/9af65bf5-b682-445f-92ee-da2b04a4b9d8)

**Comment by b1344941657** [comment]
> 我注意到动图中提示“无法完成额外备份”，是否是修改设置后没有保存呢？

我再次尝试以后发现果然是这样，因为之前修改设置以后再次回到设置界面发现那个选项还是我修改后的样子以为已经保存成功了，抱歉大佬。。。
另外如果能在修改完设置以后切换到其他界面时弹出提示让保存设置否则无法生效，这样可以避免此类问题的出现

**Comment by mcthesw** [comment]
Ok，后面我会加上醒目提示，再次感谢你的反馈，看来界面和反馈在易用性上仍然有待改进
