### ISSUE TITLE
[功能/FEATURE] 批量删除存档

### ISSUE THREAD

**Issue by bennyyip** [mcthesw/game-save-manager#127]
**新功能描述 Describe the feature**
批量删除不需要的存档，我想象的介面是每个存档左边有checkbox，勾选后点上方「批量删除」按钮删除。
真正删除前弹窗确认有描述的存档
![image](https://github.com/mcthesw/game-save-manager/assets/7467687/4eb9ee9f-acbc-4ec4-9ee5-06d9d209c225)

**应用场景简述 Application scenario**
大量存档都是跑图用的存档，后续已经不再需要了，只想保留boss前、开新周目前等关键存档。

**Comment by mcthesw** [comment]
这个功能确实有用，已经加入到未来开发计划中，感谢反馈

**Comment by mcthesw** [comment]
dev分支已经实现该功能，预计同1.3.0版本一同发布
![image](https://github.com/user-attachments/assets/d7dc190c-7a44-4eeb-8f03-e73bfe1dd504)
