### ISSUE TITLE
[功能/FEATURE]添加游戏 添加存档增加滚动条

### ISSUE THREAD

**Issue by Goojoe** [mcthesw/game-save-manager#131]
存档太多了没有滚动条, 会导致看不到后面需要备份的文件

**Comment by mcthesw** [comment]
收到，能提供一下界面截图吗，定位问题后应该下个版本就能修复

**Comment by Goojoe** [comment]
# 未全屏
![image](https://github.com/user-attachments/assets/f833ff76-f3a8-4adb-a609-e39c87dd4fa9)
# 已全屏
![image](https://github.com/user-attachments/assets/87e22946-cf04-4f62-9905-b8eee9e80218)

**Comment by Goojoe** [comment]
如果存档列表大于窗口边界,下面的存档列表就看不到了

**Comment by mcthesw** [comment]
该问题在dev分支已经修复，预计下版本一同发布
![image](https://github.com/user-attachments/assets/db0495f3-c4c5-46fb-bb7b-f83af5a67c15)
