### ISSUE TITLE
[错误/BUG] 1.3.0于windows11无法运行，1.2.0无法添加游戏

### ISSUE THREAD

**Issue by iplanc** [mcthesw/game-save-manager#141]
**问题简述 Describe the bug**
1.3.0于windows11无法运行，1.2.0添加游戏时提示出错

**环境 Desktop:**
请填写下方信息。
 Please complete the following information.
 - 操作系统 OS: Windows11
 - 软件版本 Version 1.3.0 & 1.2.0

**Comment by mcthesw** [comment]
能提供范例的config文件吗，另外，如果1.3.0版本有生成日志，可以分享一下日志文件（日志文件夹在exe同目录下）

**Comment by iplanc** [comment]
安装后无法正常生成config文件与日志文件，webview2已安装，安装及运行后目录仅有rgsm.exe与卸载程序

**Comment by mcthesw** [comment]
这样的话就很奇怪了，难道是权限问题导致无法生成？要不然试试便携版在一个肯定没有特殊权限的文件夹启动？

**Comment by iplanc** [comment]
便携版在onedrive中正常运行，这次还找到了一些新问题，我会新开一个issue
