### ISSUE TITLE
[错误/BUG] 设置中切换暗黑模式的switch状态异常 & 展开存档管理游戏列表卡顿

### ISSUE THREAD

**Issue by iplanc** [mcthesw/game-save-manager#143]
**问题简述 Describe the bug**
1. 设置中切换暗黑模式的switch保持在false，但功能正常可以切换
2. 展开与收起左上角的存档管理游戏列表时明显卡顿

**如何触发错误 To Reproduce**
1. 切换暗黑模式
    1. 默认暗色，切换暗黑模式，界面变为亮色模式，但开关状态不变
2. 展开管理游戏列表
    1. 展开与收起管理游戏列表出现明显卡顿

**正确表现 Expected behavior**
1. 暗黑模式开关随模式正确切换
2. 展开与收起游戏列表时无明显卡顿

**环境 Desktop:**
请填写下方信息。
 Please complete the following information.
 - 操作系统 OS: Windows11 23H2
 - 软件版本 Version 1.3.0

**Comment by mcthesw** [comment]
问题1已经复现，预计下版本可以修复;
问题2正在测试

**Comment by mcthesw** [comment]
#145 已经修复了问题1

**Comment by mcthesw** [comment]
问题2未能复现，群里让其他群友也没有复现卡顿
