### ISSUE TITLE
[错误/BUG]蓝奏云链接无法打开

### ISSUE THREAD

**Issue by mifazhan** [mcthesw/game-save-manager#16]
**问题简述 Describe the bug**
请用简要清晰的语言描述一下这个错误发生在何时何处。

**如何触发错误 To Reproduce**

你可以用这样的方式来描述：
1. 进入'...'界面
2. 单击'...'按钮
3. '...'发生了'...'

**正确表现 Expected behavior**
请简要描述正常时应该发生什么？（就是在BUG修好之后）

**截图 Screenshots**
如果可以的话，请用一些截图描述发生的问题。

**环境 Desktop:**
请填写下方信息。
 Please complete the following information.
 - 操作系统 OS: [e.g. iOS]
 - 软件版本 Version [e.g. 22]

**其余信息 Additional context**
你可以在这补充更多信息。

**Comment by mcthesw** [comment]
已替换链接
