### ISSUE TITLE
[错误/BUG] 额外备份未兼容存档文件夹不存在的情况

### ISSUE THREAD

**Issue by mike1936** [mcthesw/game-save-manager#171]
**问题简述 Describe the bug**

目标存档文件夹不存在导致无法应用存档

**如何触发错误 To Reproduce**

1. 机器A，使用工具，添加某个游戏，仅设定一个存档文件夹，并执行【创建新存档】
2. 机器B，将工具的所有文件复制（包含已创建的存档），开始使用工具，执行 【用最新存档覆盖】
3. 因为机器B里的这个游戏是初次安装，可能有 这个存档文件夹 一开始就**不存在** 的情况，这时会弹出
```
由于文件不存在，无法完成额外备份(覆盖前备份)，恢复中止。如果不需要该功能，请在设置中关闭。
```

在全局设置里关闭 `在应用存档时进行额外备份（在 ./save_data/游戏名/extra_backup 文件夹内）` 仍然弹出同样的错误，导致无法应用存档

**应用场景简述 Application scenario**

将存档迁移到新机器，或者游戏全部删掉重新安装时可能会出现该问题

**Comment by mcthesw** [comment]
可能因为关闭设置后没有保存设置。后期考虑将设置选项变为即时生效

**Comment by mike1936** [comment]
> 可能因为关闭设置后没有保存设置。后期考虑将设置选项变为即时生效

的确是因为没有保存设置的原因，仔细看了一下保存设置的按钮跟下面的语言选项 & 启动页面的下拉菜单视觉上很相似，下意识以为那几个按钮也是某些配置选项。

或许可以考虑将关键操作按钮的Label改为 图标+文字描述，或者改为使用主色调（蓝色）的按钮，像存档管理界面、添加游戏界面那样。

**Comment by mcthesw** [comment]
新版中已经设置实时更新，下个版本即可实装
