### ISSUE TITLE
[功能/FEATURE]建议增加编辑描述和打开存档位置的功能

### ISSUE THREAD

**Issue by BinShaw** [mcthesw/game-save-manager#2]
编辑描述方便忘记添加描述时补充
增加打开存档位置可以更直观的看到存在哪里了，也更便捷

**Comment by mcthesw** [comment]
第一个问题在内测版时已经有人反馈了，确实需要增加该功能，在我之后比较闲时应该会加上
第二个问题是想说这个软件备份的位置吗？它们都是在软件安装位置的save_data文件夹下的，你是认为要提供这个的快捷打开吗

**Comment by mcthesw** [comment]
功能2已经实现

**Comment by noneSycamore** [comment]
我想他的意思应该是：增加一个“打开存档位置”的按钮，

即，打开游戏的存档位置。说的应该不是备份的位置。

---

不过，存档文件/文件夹可以有多个，那么或许可以结合这个功能： #52 

把显示存档位置做成一个列表（默认收起的），同时固定一个“打开”按钮。
选中了某个存档位置之后，点击打开就能打开文件所在位置/文件夹

**Comment by mcthesw** [comment]
好想法

**Comment by noneSycamore** [comment]
竟然回复这么快吗...
我是这么想的：

![image](https://github.com/mcthesw/game-save-manager/assets/89766557/f8ad4639-ca8e-41a2-a1f1-b669015ea1e4)

**Comment by mcthesw** [comment]
你说的这样我觉得是可行的，近期我也要重新开工了，终于有一点时间来重新捡起这个软件了

**Comment by mcthesw** [comment]
完成“显示游戏的存档位置”，可以单击复制地址，而非打开，详见Issue #52 和PR #57

**Comment by mcthesw** [comment]
编辑描述功能完成
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/1bb9e959-eaf1-4d16-ae51-3f59f5e2b7d1)
