### ISSUE TITLE
[功能/FEATURE]自动识别地址前缀

### ISSUE THREAD

**Issue by b1344941657** [mcthesw/game-save-manager#21]
**新功能描述 Describe the feature**

存档的地址能不能默认自动识别   C:\Users\当前账户  ，在找到存档位置后隐去，不论什么设备，账户名是否相同都可以快速恢复存档，
比如修改页面的勇敢的哈克实际存档目录是
C:\Users\Bai\AppData\LocalLow\blingame
找到目录后自动隐去前半截而显示
-AppData\LocalLow\blingame
从而达到换设备换系统可以不需要修改存档目录直接使用

**Comment by mcthesw** [comment]
Duplicate of #17 
重复了，这个功能预计在v1.0.x实现，不过具体实现得仔细考虑一下，因为这个软件目前是跨平台而非单独为win服务的（不过真的有其它系统的用户吗）
