### ISSUE TITLE
[功能/FEATURE]增加一键（备份\恢复）所有存档按钮

### ISSUE THREAD

**Issue by b1344941657** [mcthesw/game-save-manager#22]
**新功能描述 Describe the feature**

增加一键（备份\恢复）所有存档按钮
一键恢复所有游戏存档按钮可以提示高危功能需要确认三次

**应用场景简述 Application scenario**
在重装系统时，很有用

**Comment by b1344941657** [comment]
在重装系统或者多设备使用的时候，配合自动识别目录的账户地址前缀将会很有用

**Comment by mcthesw** [comment]
这个功能可以有，实现起来也不难，预计v1.1可以加入
但是由于在筹划v1.0的一次阶段性大更新，所以具体实现还需要更多时间

**Comment by hmy1210** [comment]
看到作者还在回复，那我就安心的支持了~

**Comment by mcthesw** [comment]
> 看到作者还在回复，那我就安心的支持了~

@hmy1210 
其实近期在憋大更新，已经做好了，性能有大幅度提升,体积大幅度下降，但是由于几乎完全重写了一次，我还需要可能一个月来做安全性检查，毕竟存档还是很珍贵的。
感谢你的支持~

**Comment by hmy1210** [comment]
> 

要是早点有好用的存档备份管理，我很多游戏都不至于烂尾了。都是玩到一半，就重装了。

**Comment by b1344941657** [comment]
> 

这个已经很好用了，我现在主力就是用这个，以前的话是手动备份，很麻烦，这个极大的降低了工作量

**Comment by b1344941657** [comment]
> 这个功能可以有，实现起来也不难，预计v1.1可以加入 但是由于在筹划v1.0的一次阶段性大更新，所以具体实现还需要更多时间

来催更了，看看大版本多久能干完活haha

**Comment by mcthesw** [comment]
说来惭愧，最近是真的琐事缠身，可能到1月才能静下心来更新了。
前段时间[1.0.0 Alpha Release](https://github.com/mcthesw/game-save-manager/releases/tag/1.0.0-alpha.1)已经发布了，但是还存在一些问题，等实现该issue提到的功能，可能会比目前几个重要的事情晚一些：
1. 支持从老版本升级（这次升级跨度很大，所以调整会有一些难度）
2. 修改存档描述

不过好消息是主要特性都已经重新实现了，也多了支持多文件的功能，不过我还想有一些更能保证稳定性的机制和测试，这些也是在考虑中的

**Comment by mcthesw** [comment]
功能已完成，近期1.0即将发布
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/e9a37d2e-8fdd-41ed-884b-62891204d27c)
