### ISSUE TITLE
[功能/FEATURE]建议可以修改已保存的存档

### ISSUE THREAD

**Issue by BaiGei-King** [mcthesw/game-save-manager#3]
我保存了很多存档，加载了某个存档后，进行了一些修改，无法直接在原存档的基础上保存，只能创建新的存档

**Comment by mcthesw** [comment]
这个功能我得仔细考虑一下，我的建议是在描述栏使用一个特定的词语作为tag，这样可以使用搜索功能来让它们一起显示，作为一个系列存档

**Comment by mcthesw** [comment]
最终我觉得还是上方说的“Tag”方案更好，不过我觉得可以添加一个修改存档描述以方便你创建Tag
