### ISSUE TITLE
[功能/FEATURE]增加日志系统

### ISSUE THREAD

**Issue by mcthesw** [mcthesw/game-save-manager#37]
参考[Rust Cookbook](https://rustwiki.org/zh-CN/rust-cookbook/development_tools/debugging/log.html)
以及[Tauri plugin log](https://github.com/tauri-apps/tauri-plugin-log)
有建议吗

**Comment by AsterNighT** [comment]
rust log库需要一个实现后端，例子里的env_logger甚至不支持把log写到文件里，除非这log不需要持久化（不太现实，至少issue总是需要Log文件来debug），不然总是需要选一个更全面的后端。
这个tauri plugin log看上去和tauri生态比较贴合，但我不太懂tauri……

**Comment by mcthesw** [comment]
感谢你给出的建议，我近期做的其它项目也有实现log的模块，到实现这个的时候应该会有更丰富的经验

**Comment by mcthesw** [comment]
https://github.com/tauri-apps/tauri-plugin-log

**Comment by mcthesw** [comment]
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/576508a6-a13b-466b-a4e2-ea104e6b58be)
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/472d8d63-9b4e-4174-9f07-ba3168137abc)
已经通过`tracing`系列库实现
