### ISSUE TITLE
[功能/FEATURE]游戏排序功能

### ISSUE THREAD

**Issue by b1344941657** [mcthesw/game-save-manager#47]
**新功能描述 Describe the feature**
长按拖拽，修改游戏位置，或新增加游戏排序功能

**应用场景简述 Application scenario**
玩过很多游戏，不常玩，希望将后来的常用游戏可以修改到列表最上方以方便寻找，可以新增按游戏名排序或者按字母顺序排序或者自定义顺序

**Comment by mcthesw** [comment]
这个是个很有用的建议，之后会考虑安排更新

**Comment by mcthesw** [comment]
初步设想：
- 当前游戏信息存放在软件配置文件内，数组下标即为顺序信息，可以直接通过调整这个来表示新顺序
- 设置中增添功能，可以调整位置信息
- 新加入的游戏默认放在最后

**Comment by mcthesw** [comment]
新功能完成，详见PR #60 
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/c1e18d21-e946-43a9-a68b-e917e4d447f7)
