### ISSUE TITLE
[功能/FEATURE]建议增加自动备份的功能开关

### ISSUE THREAD

**Issue by Mintcolour** [mcthesw/game-save-manager#5]
比如在运行游戏时每五分钟或者每10分钟自动进行一次备份

**Comment by mcthesw** [comment]
我仔细想了一下，还是没有想到这个功能的使用场景，你不妨提供更详细的信息来描述它
我目前想到你说的可能是这样：
该软件在关闭后并不退出，而在后台运行，持续监测已知游戏的运行状态，并且定时备份这个游戏的存档

那么就会有以下问题需要解决：
- 该软件并没有打算做后台功能，如果要做的话就是全新的一个模块，需要慎重考虑
- 该软件想要做到利用到的权限尽量少，如果要持续监测游戏运行的话恐怕有些困难
- 定时备份的意义可能并不重大，你能描述一下你的具体应用场景吗
- 定时备份可能会与游戏内的自动存档冲突，导致存档损坏（不论是备份的还是游戏自身的）

所以希望你能提供更多信息，以让我搞清楚这个要求具体该不该、该怎样加入

**Comment by iPlanC** [comment]
可能是在启动游戏时 和 游戏进程结束时分别备份一下

**Comment by mcthesw** [comment]
> 可能是在启动游戏时 和 游戏进程结束时分别备份一下 @mcthesw

那么由于上面所述的原因，短期内应该还是不会加入

**Comment by iplanc** [comment]
脑子抽了，居然没想到OneDrive方案，把程序放到OneDrive网盘，这样备份的存档也会一并放入OneDrive自动同步

**Comment by mcthesw** [comment]
这么考虑的话，坚果云也提供备份文件夹的功能，不过最优肯定是接入WebDAV，而且不同设备存档位置可能不同也是个问题

**Comment by mcthesw** [comment]
这个功能在新版有了实现的可能性，因为新版的Rust内核占用极小，可以在没有开界面时几乎无占用

**Comment by mcthesw** [comment]
记录一下可能会用到的[参考文档](https://tauri.app/v1/guides/features/system-tray/)
设想：
- 设置中可以选择是否允许后台运行
- 进入某个游戏的存档控制界面，可以开启定时存档功能
  - 一个问题，我该何时停止间隔时间存档呢？检测进程是否存在？
- 通过tray显示在桌面右下角，方便退出该软件或进行快捷操作
  - 比如选定指定游戏，然后进行定时存档、快捷恢复等功能

**Comment by mcthesw** [comment]
关联 #36 ，都需要tray实现

**Comment by mcthesw** [comment]
#70 已完成，在游戏管理界面启用后
![ca6d48e74c3d9d84055d1cca4ceec347](https://github.com/mcthesw/game-save-manager/assets/61224072/e94a001f-e8dc-4c6e-8bee-8a774d54e442)
