### ISSUE TITLE
[错误/BUG]程式闪退

### ISSUE THREAD

**Issue by ghost** [mcthesw/game-save-manager#51]
**问题简述 Describe the bug**

请问有支持 windows 8.1 的系统吗?
因为无法正常开启直接闪退.
[Bleeding edge/前沿版本]
[1.0.0 Alpha Release]

这两个版本都一样.

**Comment by mcthesw** [comment]
抱歉目前没有在低于win10的windows系统上测试过，该程序在windows平台依赖于 WebView2，你可以从[这个地方](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/)下载，理论上安装WebView2后最低可以支持到win7
最近很长一段时间我比较繁忙，暂时无力更新，到之后可以优化老版本操作系统的体验（比如自动安装WebView2），但是近期只能手动安装测试一下了
另外，我想了解你是使用portable版本还是setup安装程序，根据另外一个贡献者所说，这两个在没有WebView2的情况下表现不同

标记一下修复时需要用到的[参考文档](https://tauri.app/zh-cn/v1/guides/building/windows/)

**Comment by ghost** [comment]
你好:

我是portable版本的,测试了一下确实没用安装WebView2引起的

**Comment by mcthesw** [comment]
最终决定在文档中说明win7如何使用portable版本，因为如果内置webview2体积会过于庞大，而msi安装包可以在线下载
