### ISSUE TITLE
[功能/FEATURE] 建议增加文件夹排除

### ISSUE THREAD

**Issue by ZHAN2006** [mcthesw/game-save-manager#53]
加个文件夹排除功能吧
有些游戏喜欢把mod放存档目录里
一起备份占用太高了

**Comment by mcthesw** [comment]
现v1.X版本支持选择文件和文件夹备份，直接选取需要备份的文件即可，因此该问题可以算是已经解决了
值得注意的是当前1.X版本是测试版，并不兼容之前的存档格式，需要重新安装，如果需要使用之前的存档可能需要等待更新（我在元旦之前都不会有时间了TAT）

**Comment by ZHAN2006** [comment]
你可能理解错了，我的意思是

**Comment by ZHAN2006** [comment]
你可能理解错了，我的意思是 比如备份’新建文件夹‘但要排除掉mod文件夹

+--- 新建文件夹
|   +--- app
|   +--- if
|   +--- mod
|   +--- 新建 文本文档 (2).txt
|   +--- 新建 文本文档.txt

**Comment by mcthesw** [comment]
我知道，我的意思就是现在完全可以同时选择你给的例子中的
- app
- if
- 新建 文本文档 (2).txt
- 新建 文本文档.txt

不过考虑到这样备份的目标就不是“新建文件夹”了，可能会在文件数量很多时变得很麻烦，这确实是个值得考虑的单独功能，不过增添这个功能可能会比较麻烦，你觉得怎么样呢

**Comment by ZHAN2006** [comment]
行吧
