### ISSUE TITLE
[功能/FEATURE]新增打开备份文件夹

### ISSUE THREAD

**Issue by mcthesw** [mcthesw/game-save-manager#7]
**新功能描述 Describe the feature**
在每个游戏的管理界面显示“打开备份文件夹”按钮，以快速寻找到备份的存档位置
或许还可以做一个“打开游戏存档位置”的按钮

**应用场景简述 Application scenario**
手动管理存档时会更方便

**潜在问题**
存档文件和json文件是高度耦合，对于本应用程序来说，需要增加检查json和本地存档对应的模块，以防止未预料的情况发生

**Comment by wula11** [comment]
可以的话，能不能加一个打开游戏地址的按键呢？（我知道steam有打开本地文件，但是个别情况很麻烦-如steam无法登录和离线启动等）
当未填写游戏启动地址的时候，这个按键隐藏。

另外，确实需要打开游戏存档地址的按键。目前3.0“打开备份文件夹”主要在做的事是拿来改备注……（看到你说要增加这个功能了）

**Comment by mcthesw** [comment]
@wula11 
现在有一个“打开游戏”的功能，你说的是打开游戏所在文件夹是吗？这个功能确实可以考虑，要不提交一个issue？这样之后我可以跟进完成情况
其实不论是“改备注”还是“打开备份文件夹”什么的，我都很早想做了，但是近期太忙了，更新需要一些时间
谢谢你的回应

**Comment by mcthesw** [comment]
#12 这个PR正在解决这个问题，待我 Review 完成就可以合并了

**Comment by b1344941657** [comment]
希望在主页添加一个一键备份所有已经添加的游戏的按键，在重装系统的时候特别有用，另外我还遇到一个问题，存档的地址能不能默认自动识别一下是 C:\Users\当前账户  我重装系统遇到两次了，账户名改变以后还得手动一个一个更改，如果只输入账户名后面的地址会更方便一些，这是我用了大半年之后遇到的问题。。。。
