### ISSUE TITLE
[功能/FEATURE]增强对高数量游戏管理的体验

### ISSUE THREAD

**Issue by mcthesw** [mcthesw/game-save-manager#83]
**新功能描述 Describe the feature**
需要完成以下任务（有待讨论如何完成）：
- 优化左栏（或许可以参考Steam，但是具体方案如何完成有待讨论）
- 增加搜索功能（游戏很多的时候翻找麻烦，最好支持拼音）
- 分类
- 待补充

**Comment by mcthesw** [comment]
单独做个游戏列表，然后可选将游戏pin到左栏怎么样？

**Comment by mcthesw** [comment]
需要能直接搜索游戏
需要能按照最后修改时间筛选@ASDZ_阿斯

**Comment by zfowed** [comment]
> 单独做个游戏列表，然后可选将游戏pin到左栏怎么样？

格局打开点不要限制只做存档，搞个游戏库管理工具不香嘛😀，可以参考其他管理游戏的界面：
![image](https://github.com/mcthesw/game-save-manager/assets/23629388/0fd8a578-facc-4d03-abc6-eae3d286e38e)

还有希望可以像steam一样，启动/退出游戏的时候自动加载/备份存档一次😊

**Comment by mcthesw** [comment]
@zfowed 
如果说做“游戏库管理”的话，除了存档还有什么需要管理呢？游戏设置？watt toolkit我以前用过，是个不错的工具
启动/退出游戏的时候自动备份存档这个功能可以加入到未来的特性列表中，不过开发细节我目前还没什么头绪

**Comment by zfowed** [comment]
> @zfowed 如果说做“游戏库管理”的话，除了存档还有什么需要管理呢？游戏设置？watt toolkit我以前用过，是个不错的工具 启动/退出游戏的时候自动备份存档这个功能可以加入到未来的特性列表中，不过开发细节我目前还没什么头绪

 这是我以前的想法，奈何实力不允许未能实现😂
![aaa](https://github.com/mcthesw/game-save-manager/assets/23629388/29b3c33f-e8e9-40ac-beac-2b20201ed99f)

**Comment by mcthesw** [comment]
游戏设计的功能写的很全啊，现在里面功能大都零零散散的有人实现了，不过没有一个All in one的。不过目前存档管理器开发人手不足，社区也还不活跃，暂时精力还是只能集中在存档管理方面

**Comment by mcthesw** [comment]
于1.2.0版本已经增加收藏夹功能，可以完成分类、优化左栏
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/c3424020-f610-4a01-b191-b4abe1639a0f)

**Comment by licc0000** [comment]
建议修改（影响体验的问题）

1. 关闭后，从托盘打开， 不能记录上次窗口退出时的状态（如：位置. 大小. 菜单栏/收藏栏）

2. 不能修改，游戏启动的路径 / 游戏存档路径


补充：

1. 希望能实现（单个游戏）的上传和下载
2. 如果能在软件中自定义 增加删除文件 就更好了
3. 希望能增加游戏图片的选项，能够云保存 游戏图片，（比干巴巴的文字好看）
（排版的话. 希望参考 D启动 ）我发个图你参考下【图1】

注：
1.做软件确实不容易，博主加油ヾ(◍°∇°◍)ﾉﾞ
2.我不懂编程，也学着用易语言做过一个本地的简易（哈哈哈）【图2】
3.所以我很希望能有个好用的云备份
4.有的游戏存档很大，比如环世界，一个就要几十M，一个游戏十个档就是上百M，很有可能上G
（能有个更新中... 更新完成的提示，就更完美了）

总之，希望这个软件越来越好用ヾ(◍°∇°◍)ﾉﾞ
![D 快捷启动](https://github.com/user-attachments/assets/01e8c9b4-d9e3-4dc8-92e9-0920137d2006)
![明日香 本地游戏存档备份](https://github.com/user-attachments/assets/dd33c558-96d7-4017-b55b-f059722093df)

**Comment by mcthesw** [comment]
@licc0000 感谢你的反馈，建议将内容移动到新的Issue中，方便后续的追踪，建议分为两个Issue，分别是“记录上次窗口退出时的状态”和“允许修改游戏启动的路径 / 游戏存档路径”，这些都属于Feature Request。

接下来对你说的问题进行回答：
1. “记录窗口退出前状态”是有用的，将会纳入更新计划（建议提交一个Issue，不然我可能会忘记）
2. “允许修改游戏启动的路径 / 游戏存档路径”已经在多设备支持和云同步增强的路线图中了，完成这两个优化需要很多时间，敬请期待
3. 针对单个游戏（甚至单个存档）粒度的云同步，也在云同步增强的路线图中，需要时间，现在项目只有我在持续贡献，近期太忙了，更新速度没办法快
4. 什么叫“增加删除文件”？当前存档管理器有“覆盖前删除”选项，你的意思是专门做一个删除存档文件的按钮吗
5. 本来是有游戏图片功能的，后来砍掉了，后续可能会在前端样式重构时加上，不过优先度不高（毕竟前面几个功能是更重要的）

感谢你的鼓励！

----

更新：记录窗口状态已经设立issue，详见 #154

**Comment by licc0000** [comment]
什么叫“增加删除文件”？&nbsp;&nbsp;
嗯...也就是针对单个游戏（甚至单个存档）粒度的云同步，在这个基础上，增加个 删除云盘某个存档（相当于第三方云盘了...好像又麻烦了）


创建新存档---更新存档---启动游戏........删除改存档管理--------------上传本游戏存档到云端----------删除本游戏云存档


-------备份日期---------------描述----------
2024-10-07_15-42-08------------------------------应用-----修改----删除----------上传云端--------删除云端-----------未同步
2024-10-07_16-42-08------------------------------应用-----修改----删除----------上传云端--------删除云端-----------已同步


类似这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月7日(星期一) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mcthesw/game-save-manager] [功能/FEATURE]增强对高数量游戏管理的体验 (Issue #83)














 
@licc0000 感谢你的反馈，建议将内容移动到新的Issue中，方便后续的追踪，建议分为两个Issue，分别是“记录上次窗口退出时的状态”和“允许修改游戏启动的路径 / 游戏存档路径”，这些都属于Feature Request。
 
接下来对你说的问题进行回答：
  
“记录窗口退出前状态”是有用的，将会纳入更新计划（建议提交一个Issue，不然我可能会忘记）
 
“允许修改游戏启动的路径 / 游戏存档路径”已经在多设备支持和云同步增强的路线图中了，完成这两个优化需要很多时间，敬请期待
 
针对单个游戏（甚至单个存档）粒度的云同步，也在云同步增强的路线图中，需要时间，现在项目只有我在持续贡献，近期太忙了，更新速度没办法快
 
什么叫“增加删除文件”？当前存档管理器有“覆盖前删除”选项，你的意思是专门做一个删除存档文件的按钮吗
 
本来是有游戏图片功能的，后来砍掉了，后续可能会在前端样式重构时加上，不过优先度不高（毕竟前面几个功能是更重要的）
  
感谢你的鼓励！
