### ISSUE TITLE
[功能/FEATURE]单个存档备份支持多槽位

### ISSUE THREAD

**Issue by lulaka7** [mcthesw/game-save-manager#87]
**新功能描述 Describe the feature**
一个游戏希望可以有多个存档选择备份，比如有些游戏有多个存档槽，软件内可以选择备份1号、2号或3号位
![屏幕截图 2024-03-13 122011](https://github.com/mcthesw/game-save-manager/assets/163230649/657464bb-8070-4ba1-8675-4cdb7f3e9f65)
想分别备份savedata1或者savedata2
![屏幕截图 2024-03-13 122443](https://github.com/mcthesw/game-save-manager/assets/163230649/3f1a42da-0ef9-4ebe-80cc-3dfa808ca801)
在这里添加的话只能添加到一个压缩包里，就是想要把savedata1或者savedata2分别备份到两个压缩包里，还原的时候只用还原1或2。不知道我表述清楚没有

**应用场景简述 Application scenario**
多个存档槽位一起玩的时候，还原其中一个容易错误还原其它槽位。这样可以避免错误还原？

**Comment by mcthesw** [comment]
需要讨论一下实现的必要性以及实现途径

必要性：
1. 这种情况直接设置两个游戏是否足够方便
2. 可否通过支持自行选择文件恢复来支持（不过我又想了下，这个功能可能比较危险，也不好做）
3. 如果说会导致左栏东西变多，能否通过 #83 的改进来避免

途径：
1. 如果修改现有存档格式的话，需要进行不兼容的变更，因为这个功能实际是让一个`Game`支持多组`save_paths: Vec<SaveUnit>`
4. 如果维持现有存档格式，可以从前端修改，例如规定前缀或后缀来区分槽位，如果实现的话，这个无疑是比较方便的方案

**Comment by mcthesw** [comment]
现在更推荐使用收藏夹树来实现这个功能
![image](https://github.com/mcthesw/game-save-manager/assets/61224072/08c11fa0-75cc-4d1b-8f60-35c47721103a)
可以这样分类：

- 游戏类型1
  - 游戏名1
    - 存档位1
    - 存档位2
- 游戏类型2

可以接受现在这个解决方案吗

**Comment by lulaka7** [comment]
没问题，只要达到效果就行了。😉

Sworld ***@***.***> 于 2024年6月6日周四 23:29写道：
