### ISSUE TITLE
[错误/BUG]启动游戏无汉化

### ISSUE THREAD

**Issue by Ykr-0610** [mcthesw/game-save-manager#9]
启动文件选择的是汉化启动文件，但启动后汉化不管用了

**Comment by mcthesw** [comment]
我已经收到多个关于“启动”功能的Bug反馈，这一块会在近期重写，可能在v0.3.X的小版本中进行修复

**Comment by mcthesw** [comment]
现在“启动”按钮存在多种奇怪的错误，我需要一些时间进行整理:D

**Comment by Ykr-0610** [comment]
那我就先暂时用存档功能吧，支持。

**Comment by iPlanC** [comment]
> 启动文件选择的是汉化启动文件，但启动后汉化不管用了

可以给个测试用例吗，比如游戏文件目录的截图

**Comment by mcthesw** [comment]
新版应该解决了这个问题，不过新版需要一些时间才能发布，敬请期待
