### ISSUE TITLE
[错误/BUG] 多次运行exe后，有多个exe在同时在运行

### ISSUE THREAD

**Issue by weizhking** [mcthesw/game-save-manager#96]
**问题简述 Describe the bug**
多次运行exe后，有多个exe在同时在运行

**正确表现 Expected behavior**
对于支持退出到托盘的应用，再次运行exe应打开之前的应用

**环境 Desktop:**
Win10 22H2 x64

**Comment by mcthesw** [comment]
感谢提交问题。
该问题在版本1.0.1已经修复，详见[更新日志](https://help.sworld.club/blog/v1_0_1)
这种小版本更新不会专门发布，可能等到1.1.0会再发布一个版本，在此之前如果想要使用的话可以从[前沿测试版](https://github.com/mcthesw/game-save-manager/releases/tag/latest)中下载，目前的几次更新都可以直接覆盖升级
